	
DROP TABLE AMENITIES CASCADE CONSTRAINTS;
	
DROP TABLE CALENDAR CASCADE CONSTRAINTS;
	
DROP TABLE COSTS_DETAILS CASCADE CONSTRAINTS;
	
DROP TABLE HOST CASCADE CONSTRAINTS;
	
DROP TABLE HOST_VERIFICATIONS CASCADE CONSTRAINTS;
	
DROP TABLE HOST_DETAILS CASCADE CONSTRAINTS;
	
DROP TABLE LISTING CASCADE CONSTRAINTS;
	
DROP TABLE LISTING_AMENITIES CASCADE CONSTRAINTS;
	
DROP TABLE LISTING_DETAILS CASCADE CONSTRAINTS;
	
DROP TABLE LISTING_LOCATION CASCADE CONSTRAINTS;
	
DROP TABLE MATERIAL_DESCRIPTION CASCADE CONSTRAINTS;
	
DROP TABLE REVIEWER CASCADE CONSTRAINTS;
	
DROP TABLE REVIEWS CASCADE CONSTRAINTS;
	
DROP TABLE REVIEWS_SCORES CASCADE CONSTRAINTS;
	
DROP TABLE VERIFICATIONS CASCADE CONSTRAINTS;
